FROM node:20-alpine

WORKDIR /app


RUN npm install -g pnpm

# Install dependencies
COPY package*.json ./
RUN pnpm install

# Copy source code
COPY . .

# Set NODE_ENV for development
ENV NODE_ENV=development

# Expose default Next.js development port
EXPOSE 3000

# Start the development server
CMD ["npm", "run", "dev"]